version: '3.7'

services:

  php-fpm:
    image: thecodingmachine/php:7.4-v3-fpm-node8
    restart: on-failure
    links:
      - postgres
    networks:
      - common-network
    volumes:
      - .:/var/www/html:rw
    environment:
      DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1

  web:
    image: nginx:latest
    ports:
      - "8011:80"
    volumes:
      - .:/var/www/html:rw
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common-network
    links:
      - php-fpm
    depends_on:
      - php-fpm

  postgres:
    image: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
